const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const context = vm.createContext({Intl, Date, console, window:{addEventListener(){}}, document:{querySelector:()=>null}, setTimeout, clearTimeout});
vm.runInContext(fs.readFileSync('admin.js','utf8').replace('init();',''), context);
const run = code => vm.runInContext(code, context);
run(`state.month='2026-08'; state.attendance={};
for(const date of monthDays().filter(d=>!isClosedDay(d)&&!['2026-08-13','2026-08-14'].includes(d))) state.attendance[recordKey(date,'test')]={status:'出勤'};`);
assert.equal(run("perfectBonusFor('test')"),0);
run("state.settings.dayOverrides={'2026-08-13':'closed','2026-08-14':'closed'}");
assert.equal(run("perfectBonusFor('test')"),1000);
run("state.attendance[recordKey('2026-08-12','test')].status='欠勤'");
assert.equal(run("perfectBonusFor('test')"),0);
run("state.attendance[recordKey('2026-08-12','test')].status='在宅'");
assert.equal(run("perfectBonusFor('test')"),1000);
run("state.settings.dayOverrides['2026-08-11']='open'");
assert.equal(run("perfectBonusFor('test')"),0);
run("state.settings.dayOverrides['2026-08-11']='auto'");
assert.equal(run("perfectBonusFor('test')"),1000);
run("state.attendance[recordKey('2026-08-13','test')]={status:'出勤'}");
assert.equal(run("holidayBonusFor('test')"),500);
run("state.settings.dayOverrides['2026-08-13']='auto'");
assert.equal(run("holidayBonusFor('test')"),0);
assert.equal(run("migrateState(JSON.parse(JSON.stringify(state))).settings.dayOverrides['2026-08-14']"),'closed');
run("state.month='2026-09'");
assert.equal(run("isClosedDay('2026-09-14')"),false);
run("for(const date of monthDays()) state.settings.dayOverrides[date]='closed'");
assert.equal(run("perfectBonusFor('test')"),0);
const app = fs.readFileSync('app.js','utf8');
vm.runInContext(app.slice(app.indexOf('function normalizeState('),app.indexOf('\nfunction render()',app.indexOf('function normalizeState('))),context);
assert.equal(run("normalizeState({month:'2026-08',settings:{dayOverrides:{'2026-08-14':'closed'}}}).settings.dayOverrides['2026-08-14']"),'closed');
let html='';
context.document.querySelector=()=>({set innerHTML(value){html=value;}});
run("state.month='2026-08';renderHolidayCalendar()");
assert.equal((html.match(/<select /g)||[]).length,31);
assert.ok(html.includes('2026-08-14'));
console.log('PASS: bonus eligibility, absence, remote work, opening/reset, holiday pay, migration, month isolation, all closed, iPad preservation, 31-day calendar');
